/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg;

import org.junit.Test;
import static org.junit.Assert.*;

public class EmployeeTest {
    @Test public void testSomeLibraryMethod() {
        Employee classUnderTest = new Employee();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
